<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMtVjqMJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMtVjqMJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMtVjqMJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMtVjqMJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMtVjqMJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MtVjqMJ',
    'container.build_id' => 'ae030b48',
    'container.build_time' => 1539605264,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMtVjqMJ');
