<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIisDppL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIisDppL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIisDppL.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIisDppL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIisDppL\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IisDppL',
    'container.build_id' => '153cba7f',
    'container.build_time' => 1539642119,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIisDppL');
